[from-zadarma]
exten => _X.,1,NoOp(Zadarma inbound CALLERID=${CALLERID(num)} DID=${EXTEN})
 same => n,Stasis(callbot,inbound)
 same => n,Hangup()

exten => _+X.,1,Goto(from-zadarma,${EXTEN:1},1)
exten => s,1,Stasis(callbot,inbound)
 same => n,Hangup()

[default]
include => from-zadarma
